name: Build workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
      - name: Create mocked .env.local with required variables
        run: |
          echo MONGODB_URI=mongodb://mongo                 > .env.local
          echo MONGODB_DB=mongodb                          >> .env.local
          echo ENCRYPTION_KEY=encryption_key               >> .env.local
          echo MONGODB_URI=mongodb://mongo                 > .env.test.local
          echo MONGODB_DB=mongodb                          >> .env.test.local
          echo ENCRYPTION_KEY=encryption_key               >> .env.test.local
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
      - uses: preactjs/compressed-size-action@v2
        with:
          pattern: ".next/**/*.{js,css,html,json}"
      - name: run tests
        run: yarn test:ci --coverage
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
