name: Generate docs

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run gen:docs
      - name: Push output to docs repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DOCS_GEN_GH_TOKEN }}
        with:
          source-directory: "out"
          destination-github-username: "eutiveumsonho"
          destination-repository-name: "docs"
          user-email: marcelovicentegc.bot@gmail.com
          target-branch: main
