name: Pull request workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v4
      - name: Create mocked .env.local with required variables
        run: |
          echo MONGODB_URI=mongodb://mongo                 > .env.local
          echo MONGODB_DB=mongodb                          >> .env.local
          echo ENCRYPTION_KEY=encryption_key               >> .env.local
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install
      - run: pnpm run build
