name: Pull request workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v4
      - name: Create mocked .env.local with required variables
        run: |
          echo MONGODB_URI=mongodb://mongo                 > .env.local
          echo MONGODB_DB=mongodb                          >> .env.local
          echo ENCRYPTION_KEY=encryption_key               >> .env.local
          echo OPENAI_TOKEN=openai_api_key                 >> .env.local
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - run: pnpm install
      - run: pnpm run build
      - uses: preactjs/compressed-size-action@v2
        with:
          # Relevant issue https://github.com/preactjs/compressed-size-action/issues/25
          pattern: "{./.next/static/chunks/**/*.js,.next/static/css/*.css,.next/server/pages/*.{html,json}}"
          exclude: "{**/*.map,**/*.nft.json,**/node_modules/**}"
          strip-hash: "\\w+-(\\w{16}).js$"
