name: Test workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create mocked .env.local with required variables
        run: |
          echo MONGODB_URI=mongodb://mongo                 > .env.test,local
          echo MONGODB_DB=mongodb                          >> .env.test.local
          echo ENCRYPTION_KEY=encryption_key               >> .env.test.local
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
      - run: yarn
      - run: yarn test:ci --coverage
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
